// APP CONSTANTS
export default {
  CATEGORY: 'CATEGORY',
  CREATE_IDEA: 'CREATE_IDEA',
  LOG_IN: 'LOG_IN',
  PUBLIC_IDEAS: 'PUBLIC_IDEAS',
  SIGN_UP: 'SIGN_UP',
  RESET_PASSWORD: 'RESET_PASSWORD'
};
