// APP CONSTANTS
export default {
  CATEGORY: 'CATEGORY',
  CREATE_IDEA: 'CREATE_IDEA',
  DELETE_IDEA: 'DELETE_IDEA',
  FETCH_COMMENT: 'FETCH_COMMENT',
  FETCH_IDEA: 'FETCH_IDEA',
  LOG_IN: 'LOG_IN',
  MY_IDEAS: 'MY_IDEAS',
  PUBLIC_IDEAS: 'PUBLIC_IDEAS',
  SEARCH_IDEA: 'SEARCH_IDEA',
  CREATE_COMMENT: 'CREATE_COMMENT',
  SIGN_UP: 'SIGN_UP',
  RESET_PASSWORD: 'RESET_PASSWORD',
  UPDATE_IDEA: 'UPDATE_IDEA',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD'
};
